### ISSUE TITLE
bug: Crash when try to edit playlist details 

### ISSUE THREAD

**Issue by AraAraOwO** [inotia00/revanced-integrations#40]
### Type

Cosmetic

### Bug description

It seems like setContentDescription is called because of description field in edit dialog and causes crash because of NullReference (which occurs when playlist description is not set)

### Steps to reproduce

1. Go to your profile tab
2. Try to edit playlist which have no description set 

### Relevant log output

```shell
FATAL EXCEPTION: main
Process: com.google.android.youtube, PID: 28712
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at app.revanced.integrations.youtube.patches.player.PlayerPatch.setContentDescription(PlayerPatch.java:84)
	at znn.K(PG:77)
	at znn.v(PG:10)
	at znn.b(PG:543)
	at zmy.I(PG:2014)
	at zmy.d(PG:33)
	at aclx.eV(PG:38)
	at zma.a(PG:631)
	at azsw.vX(PG:8)
	at baia.vS(PG:24)
	at bajt.vS(PG:30)
	at bagx.d(PG:81)
	at bagw.vS(PG:44)
	at balb.run(PG:19)
	at bajp.e(PG:11)
	at azpo.aL(PG:13)
	at bagy.e(PG:88)
	at azpo.aL(PG:13)
	at baju.e(PG:10)
	at azpo.aL(PG:13)
	at baib.M(PG:26)
	at azpz.L(PG:13)
	at azpz.J(PG:6)
	at azpz.I(PG:3)
	at yuw.call(PG:391)
	at xbr.vS(PG:15)
	at bahr.vS(PG:35)
	at bajt.vS(PG:30)
	at bahg.e(PG:22)
	at wsg.a(PG:276)
	at xbs.oa(PG:5)
	at bmh.a(PG:49)
	at dpi.c(PG:17)
	at bmy.b(PG:121)
	at wly.run(PG:388)
	at vcw.ay(PG:7)
	at gfp.a(PG:134)
	at bahi.e(PG:11)
	at azpo.aL(PG:13)
	at baju.e(PG:10)
	at azpo.aL(PG:13)
	at bahs.e(PG:10)
	at azpo.aL(PG:13)
	at vcw.cL(PG:10)
	at vcw.az(PG:3)
	at zot.b(PG:96)
	at ztq.h(PG:260)
	at ztq.g(PG:61)
	at yaz.run(PG:206)
	at xkn.e(PG:50)
	at xkn.b(PG:19)
	at ztq.c(PG:47)
	at ztl.c(PG:14)
	at abvz.c(PG:423)
	at ahqa.aM(PG:275)
	at ahqa.onItemClick(PG:27)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1257)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3270)
	at android.widget.AbsListView$3.run(AbsListView.java:4236)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Solution

Add a try catch or null check here
https://github.com/inotia00/revanced-integrations/blob/96db0c0b9ad8ea069e48c6ac9174b06010074b00/app/src/main/java/app/revanced/integrations/youtube/patches/player/PlayerPatch.java#L83

**Comment by AraAraOwO** [comment]
sorry if i should not have open issue here (i know about issues repo but forgot to do it there)

**Comment by inotia00** [comment]
This repo's issue page is deprecated
Instead, the following repo takes over the role of discussion and issue reporting:
https://github.com/inotia00/ReVanced_Extended/issues

This issue has been opened in the following repo:
https://github.com/inotia00/ReVanced_Extended/issues/2008

And it was fixed in commit https://github.com/inotia00/revanced-integrations/commit/f096b515b91b1cd5af65fd91bafaaed3c78ffcf6 in the dev branch last week

**Comment by AraAraOwO** [comment]
Yeah I forgot about issue repo. Anyway thanks for informing me about it
